services:
  web:
    build: .
    container_name: freelizz_web
    ports:
      - '8787:80'
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: freelizz_db
    ports:
      - '3390:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - freelizz_mysql:/var/lib/mysql

volumes:
  freelizz_mysql:
